const data = [
  {
    id: 1,
    betId: "Ag7651cdgh6348684bhj24hkb",
    totalStake: 100.0,
    totalOdds: 43.2,
    betStatus: "Lost",
    date: "Oct 19",
    betLogo: "🏅",
    team1: "Manchester",
    team1Logo: "🏅",
    team2: "Chelsea",
    team2Logo: "🏅",
    scores: "4 : 0",
    odd: 4.94,
    gameStatus: "Lost",
  },

  {
    id: 2,
    betId: "Ag76byj78cgghn2684bhj24hkb",
    totalStake: 400.0,
    totalOdds: 143.2,
    betStatus: "Lost",
    date: "July 19",
    betLogo: "🏅",
    team1: "Liverpool city",
    team1Logo: "⚾",
    team2: "Man united",
    team2Logo: "🏀",
    scores: "2 : 0",
    odd: 41.94,
    gameStatus: "Lost",
  },

  {
    id: 3,
    betId: "Ag76098jkn348684bhj24hkb",
    totalStake: 200.0,
    totalOdds: 143.2,
    betStatus: "Lost",
    date: "Sep 19",
    betLogo: "🏅",
    team1: "Juventus city",
    team1Logo: "⚾",
    team2: "Arsenal",
    team2Logo: "⚽",
    scores: "3 : 2",
    odd: 14.94,
    gameStatus: "Lost",
  },

  {
    id: 4,
    betId: "Ag765ghbyj34868x543nhg4hkb",
    totalStake: 500.0,
    totalOdds: 23.2,
    betStatus: "Lost",
    date: "Oct 19",
    betLogo: "🏅",
    team1: "Doncaster city",
    team1Logo: "⚾",
    team2: "Nigeria",
    team2Logo: "⚽",
    scores: "1 : 5",
    odd: 54.94,
    gameStatus: "Lost",
  },
];

let myData = data;
export default { myData };
